// Catálogo global de destinos Tropicco — todos os países do mundo.
// Países com paginaEstatica têm página completa publicada.
// Os demais aparecem como "em curadoria" via destinos/destino.html?slug=X

window.TODOS_PAISES = [

  // ═══════════════════════════════════════════════════ EUROPA
  { slug:'albania',              nome:'Albânia',                continente:'Europa',   coords:{lat:41.1,lng:20.2}, capital:'Tirana'                },
  { slug:'alemanha',             nome:'Alemanha',               continente:'Europa',   coords:{lat:51.2,lng:10.5}, capital:'Berlim'                },
  { slug:'andorra',              nome:'Andorra',                continente:'Europa',   coords:{lat:42.5,lng:1.5},  capital:'Andorra la Vella'      },
  { slug:'armenia',              nome:'Armênia',                continente:'Europa',   coords:{lat:40.1,lng:45.0}, capital:'Ierevan'               },
  { slug:'austria',              nome:'Áustria',                continente:'Europa',   coords:{lat:47.5,lng:13.5}, capital:'Viena'                 },
  { slug:'azerbaijao',           nome:'Azerbaijão',             continente:'Europa',   coords:{lat:40.1,lng:47.6}, capital:'Baku'                  },
  { slug:'belgica',              nome:'Bélgica',                continente:'Europa',   coords:{lat:50.8,lng:4.5},  capital:'Bruxelas'              },
  { slug:'bielo-russia',         nome:'Bielorrússia',           continente:'Europa',   coords:{lat:53.7,lng:27.9}, capital:'Minsk'                 },
  { slug:'bosnia',               nome:'Bósnia e Herzegovina',   continente:'Europa',   coords:{lat:44.2,lng:17.9}, capital:'Sarajevo'              },
  { slug:'bulgaria',             nome:'Bulgária',               continente:'Europa',   coords:{lat:42.7,lng:25.5}, capital:'Sofia'                 },
  { slug:'chipre',               nome:'Chipre',                 continente:'Europa',   coords:{lat:35.1,lng:33.4}, capital:'Nicósia'               },
  { slug:'croacia',              nome:'Croácia',                continente:'Europa',   coords:{lat:45.1,lng:15.2}, capital:'Zagreb'                },
  { slug:'dinamarca',            nome:'Dinamarca',              continente:'Europa',   coords:{lat:56.3,lng:9.5},  capital:'Copenhague'            },
  { slug:'eslovaquia',           nome:'Eslováquia',             continente:'Europa',   coords:{lat:48.7,lng:19.5}, capital:'Bratislava'            },
  { slug:'eslovenia',            nome:'Eslovênia',              continente:'Europa',   coords:{lat:46.2,lng:14.8}, capital:'Liubliana'             },
  { slug:'espanha',              nome:'Espanha',                continente:'Europa',   coords:{lat:40.5,lng:-3.7}, capital:'Madri'                 },
  { slug:'estonia',              nome:'Estônia',                continente:'Europa',   coords:{lat:58.6,lng:25.0}, capital:'Tallinn'               },
  { slug:'finlandia',            nome:'Finlândia',              continente:'Europa',   coords:{lat:64.0,lng:26.0}, capital:'Helsinque'             },
  { slug:'franca',               nome:'França',                 continente:'Europa',   coords:{lat:46.2,lng:2.2},  capital:'Paris'                 },
  { slug:'georgia',              nome:'Geórgia',                continente:'Europa',   coords:{lat:42.3,lng:43.4}, capital:'Tbilisi'               },
  { slug:'grecia',               nome:'Grécia',                 continente:'Europa',   coords:{lat:39.1,lng:22.0}, capital:'Atenas',               paginaEstatica:'grecia.html'    },
  { slug:'hungria',              nome:'Hungria',                continente:'Europa',   coords:{lat:47.2,lng:19.5}, capital:'Budapeste'             },
  { slug:'irlanda',              nome:'Irlanda',                continente:'Europa',   coords:{lat:53.4,lng:-8.2}, capital:'Dublin'                },
  { slug:'islandia',             nome:'Islândia',               continente:'Europa',   coords:{lat:64.9,lng:-18.2},capital:'Reiquiavique'          },
  { slug:'italia',               nome:'Itália',                 continente:'Europa',   coords:{lat:42.5,lng:12.5}, capital:'Roma',                 paginaEstatica:'italia.html'    },
  { slug:'kosovo',               nome:'Kosovo',                 continente:'Europa',   coords:{lat:42.6,lng:20.9}, capital:'Pristina'              },
  { slug:'letonia',              nome:'Letônia',                continente:'Europa',   coords:{lat:56.9,lng:24.6}, capital:'Riga'                  },
  { slug:'liechtenstein',        nome:'Liechtenstein',          continente:'Europa',   coords:{lat:47.1,lng:9.6},  capital:'Vaduz'                 },
  { slug:'lituania',             nome:'Lituânia',               continente:'Europa',   coords:{lat:55.2,lng:24.0}, capital:'Vilnius'               },
  { slug:'luxemburgo',           nome:'Luxemburgo',             continente:'Europa',   coords:{lat:49.8,lng:6.1},  capital:'Luxemburgo'            },
  { slug:'malta',                nome:'Malta',                  continente:'Europa',   coords:{lat:35.9,lng:14.4}, capital:'Valeta'                },
  { slug:'moldavia',             nome:'Moldávia',               continente:'Europa',   coords:{lat:47.4,lng:28.4}, capital:'Chisinau'              },
  { slug:'monaco',               nome:'Mônaco',                 continente:'Europa',   coords:{lat:43.7,lng:7.4},  capital:'Mônaco'                },
  { slug:'montenegro',           nome:'Montenegro',             continente:'Europa',   coords:{lat:42.7,lng:19.4}, capital:'Podgorica'             },
  { slug:'noruega',              nome:'Noruega',                continente:'Europa',   coords:{lat:60.5,lng:8.5},  capital:'Oslo'                  },
  { slug:'paises-baixos',        nome:'Países Baixos',          continente:'Europa',   coords:{lat:52.1,lng:5.3},  capital:'Amsterdã'              },
  { slug:'polonia',              nome:'Polônia',                continente:'Europa',   coords:{lat:52.1,lng:19.4}, capital:'Varsóvia'              },
  { slug:'portugal',             nome:'Portugal',               continente:'Europa',   coords:{lat:39.6,lng:-8.0}, capital:'Lisboa',               paginaEstatica:'portugal.html'  },
  { slug:'reino-unido',          nome:'Reino Unido',            continente:'Europa',   coords:{lat:54.0,lng:-2.0}, capital:'Londres'               },
  { slug:'republica-tcheca',     nome:'República Tcheca',       continente:'Europa',   coords:{lat:49.8,lng:15.5}, capital:'Praga'                 },
  { slug:'romenia',              nome:'Romênia',                continente:'Europa',   coords:{lat:45.9,lng:24.9}, capital:'Bucareste'             },
  { slug:'russia',               nome:'Rússia',                 continente:'Europa',   coords:{lat:60.0,lng:100.0},capital:'Moscou'                },
  { slug:'san-marino',           nome:'San Marino',             continente:'Europa',   coords:{lat:43.9,lng:12.5}, capital:'San Marino'            },
  { slug:'servia',               nome:'Sérvia',                 continente:'Europa',   coords:{lat:44.0,lng:21.0}, capital:'Belgrado'              },
  { slug:'suecia',               nome:'Suécia',                 continente:'Europa',   coords:{lat:60.1,lng:15.0}, capital:'Estocolmo'             },
  { slug:'suica',                nome:'Suíça',                  continente:'Europa',   coords:{lat:46.8,lng:8.2},  capital:'Berna',                paginaEstatica:'suica.html'     },
  { slug:'ucrania',              nome:'Ucrânia',                continente:'Europa',   coords:{lat:49.0,lng:32.0}, capital:'Kiev'                  },
  { slug:'vaticano',             nome:'Vaticano',               continente:'Europa',   coords:{lat:41.9,lng:12.45},capital:'Cidade do Vaticano'    },

  // ═══════════════════════════════════════════════════ ÁSIA
  { slug:'afeganistao',          nome:'Afeganistão',            continente:'Ásia',     coords:{lat:33.0,lng:65.0}, capital:'Cabul'                 },
  { slug:'arabia-saudita',       nome:'Arábia Saudita',         continente:'Ásia',     coords:{lat:24.0,lng:45.0}, capital:'Riade'                 },
  { slug:'bahrein',              nome:'Bahrein',                continente:'Ásia',     coords:{lat:26.0,lng:50.6}, capital:'Manama'                },
  { slug:'bangladesh',           nome:'Bangladesh',             continente:'Ásia',     coords:{lat:23.7,lng:90.4}, capital:'Daca'                  },
  { slug:'butao',                nome:'Butão',                  continente:'Ásia',     coords:{lat:27.5,lng:90.4}, capital:'Timphu'                },
  { slug:'camboja',              nome:'Camboja',                continente:'Ásia',     coords:{lat:12.6,lng:104.9},capital:'Phnom Penh'            },
  { slug:'cazaquistao',          nome:'Cazaquistão',            continente:'Ásia',     coords:{lat:48.0,lng:68.0}, capital:'Astana'                },
  { slug:'china',                nome:'China',                  continente:'Ásia',     coords:{lat:35.9,lng:104.0},capital:'Pequim'                },
  { slug:'coreia-do-norte',      nome:'Coreia do Norte',        continente:'Ásia',     coords:{lat:40.3,lng:127.5},capital:'Pyongyang'             },
  { slug:'coreia-do-sul',        nome:'Coreia do Sul',          continente:'Ásia',     coords:{lat:36.5,lng:127.8},capital:'Seul'                  },
  { slug:'emirados-arabes',      nome:'Emirados Árabes Unidos', continente:'Ásia',     coords:{lat:23.4,lng:53.8}, capital:'Abu Dhabi'             },
  { slug:'filipinas',            nome:'Filipinas',              continente:'Ásia',     coords:{lat:12.9,lng:121.8},capital:'Manila'                },
  { slug:'india',                nome:'Índia',                  continente:'Ásia',     coords:{lat:20.6,lng:79.1}, capital:'Nova Delhi'            },
  { slug:'indonesia',            nome:'Indonésia',              continente:'Ásia',     coords:{lat:-0.8,lng:113.9},capital:'Jacarta'               },
  { slug:'iraque',               nome:'Iraque',                 continente:'Ásia',     coords:{lat:33.2,lng:43.7}, capital:'Bagdá'                 },
  { slug:'ira',                  nome:'Irã',                    continente:'Ásia',     coords:{lat:32.4,lng:53.7}, capital:'Teerã'                 },
  { slug:'israel',               nome:'Israel',                 continente:'Ásia',     coords:{lat:31.5,lng:34.8}, capital:'Tel Aviv'              },
  { slug:'japao',                nome:'Japão',                  continente:'Ásia',     coords:{lat:36.2,lng:138.3},capital:'Tóquio',               paginaEstatica:'japao.html'     },
  { slug:'jordania',             nome:'Jordânia',               continente:'Ásia',     coords:{lat:30.6,lng:36.3}, capital:'Amã'                   },
  { slug:'kuwait',               nome:'Kuwait',                 continente:'Ásia',     coords:{lat:29.3,lng:47.5}, capital:'Cidade do Kuwait'      },
  { slug:'laos',                 nome:'Laos',                   continente:'Ásia',     coords:{lat:18.0,lng:103.0},capital:'Vientiane'             },
  { slug:'libano',               nome:'Líbano',                 continente:'Ásia',     coords:{lat:33.9,lng:35.9}, capital:'Beirute'               },
  { slug:'malasia',              nome:'Malásia',                continente:'Ásia',     coords:{lat:4.2,lng:108.0}, capital:'Kuala Lumpur'          },
  { slug:'maldivas',             nome:'Maldivas',               continente:'Ásia',     coords:{lat:3.2,lng:73.2},  capital:'Malé'                  },
  { slug:'mongolia',             nome:'Mongólia',               continente:'Ásia',     coords:{lat:46.9,lng:103.8},capital:'Ulan Bator'            },
  { slug:'myanmar',              nome:'Myanmar',                continente:'Ásia',     coords:{lat:17.1,lng:96.1}, capital:'Naypyidaw'             },
  { slug:'nepal',                nome:'Nepal',                  continente:'Ásia',     coords:{lat:28.4,lng:84.1}, capital:'Catmandu'              },
  { slug:'oma',                  nome:'Omã',                    continente:'Ásia',     coords:{lat:22.0,lng:58.0}, capital:'Mascate'               },
  { slug:'paquistao',            nome:'Paquistão',              continente:'Ásia',     coords:{lat:30.4,lng:69.3}, capital:'Islamabad'             },
  { slug:'qatar',                nome:'Qatar',                  continente:'Ásia',     coords:{lat:25.4,lng:51.2}, capital:'Doha'                  },
  { slug:'quirguistao',          nome:'Quirguistão',            continente:'Ásia',     coords:{lat:41.2,lng:74.8}, capital:'Bisqueque'             },
  { slug:'singapura',            nome:'Singapura',              continente:'Ásia',     coords:{lat:1.4,lng:103.8}, capital:'Singapura'             },
  { slug:'siria',                nome:'Síria',                  continente:'Ásia',     coords:{lat:34.8,lng:39.1}, capital:'Damasco'               },
  { slug:'sri-lanka',            nome:'Sri Lanka',              continente:'Ásia',     coords:{lat:7.9,lng:80.8},  capital:'Colombo'               },
  { slug:'tailandia',            nome:'Tailândia',              continente:'Ásia',     coords:{lat:15.9,lng:100.9},capital:'Bangkok',              paginaEstatica:'tailandia.html' },
  { slug:'taiwan',               nome:'Taiwan',                 continente:'Ásia',     coords:{lat:23.8,lng:121.0},capital:'Taipei'                },
  { slug:'tajiquistao',          nome:'Tajiquistão',            continente:'Ásia',     coords:{lat:38.9,lng:71.3}, capital:'Duchanbé'              },
  { slug:'timor-leste',          nome:'Timor-Leste',            continente:'Ásia',     coords:{lat:-8.9,lng:125.7},capital:'Díli'                  },
  { slug:'turcomenistao',        nome:'Turquemenistão',         continente:'Ásia',     coords:{lat:40.0,lng:59.6}, capital:'Asgabate'              },
  { slug:'turquia',              nome:'Turquia',                continente:'Ásia',     coords:{lat:39.1,lng:35.2}, capital:'Ancara'                },
  { slug:'uzbequistao',          nome:'Uzbequistão',            continente:'Ásia',     coords:{lat:41.4,lng:64.6}, capital:'Tashkent'              },
  { slug:'vietna',               nome:'Vietnã',                 continente:'Ásia',     coords:{lat:16.5,lng:107.5},capital:'Hanói'                 },
  { slug:'iemen',                nome:'Iêmen',                  continente:'Ásia',     coords:{lat:15.6,lng:48.5}, capital:'Sanaa'                 },

  // ═══════════════════════════════════════════════════ ÁFRICA
  { slug:'africa-do-sul',        nome:'África do Sul',          continente:'África',   coords:{lat:-29.0,lng:25.1},capital:'Pretória',             paginaEstatica:'africa-do-sul.html' },
  { slug:'argelia',              nome:'Argélia',                continente:'África',   coords:{lat:28.0,lng:2.6},  capital:'Argel'                 },
  { slug:'angola',               nome:'Angola',                 continente:'África',   coords:{lat:-11.2,lng:17.9},capital:'Luanda'                },
  { slug:'benim',                nome:'Benim',                  continente:'África',   coords:{lat:9.3,lng:2.3},   capital:'Porto Novo'            },
  { slug:'botsuana',             nome:'Botsuana',               continente:'África',   coords:{lat:-22.3,lng:24.7},capital:'Gaborone'              },
  { slug:'burkina-faso',         nome:'Burkina Faso',           continente:'África',   coords:{lat:12.4,lng:-1.6}, capital:'Uagadugu'              },
  { slug:'burundi',              nome:'Burundi',                continente:'África',   coords:{lat:-3.4,lng:29.9}, capital:'Gitega'                },
  { slug:'cabo-verde',           nome:'Cabo Verde',             continente:'África',   coords:{lat:16.5,lng:-24.0},capital:'Praia'                 },
  { slug:'camaroes',             nome:'Camarões',               continente:'África',   coords:{lat:4.2,lng:11.8},  capital:'Iaundê'                },
  { slug:'chade',                nome:'Chade',                  continente:'África',   coords:{lat:15.5,lng:18.7}, capital:'Ndjamena'              },
  { slug:'comores',              nome:'Comores',                continente:'África',   coords:{lat:-11.6,lng:43.3},capital:'Moroni'                },
  { slug:'congo',                nome:'Congo',                  continente:'África',   coords:{lat:-1.0,lng:15.2}, capital:'Brazzaville'           },
  { slug:'congo-dr',             nome:'Rep. Dem. do Congo',     continente:'África',   coords:{lat:-4.0,lng:21.8}, capital:'Kinshasa'              },
  { slug:'costa-do-marfim',      nome:'Costa do Marfim',        continente:'África',   coords:{lat:7.5,lng:-5.6},  capital:'Yamussucro'            },
  { slug:'djibuti',              nome:'Djibuti',                continente:'África',   coords:{lat:11.8,lng:42.6}, capital:'Djibuti'               },
  { slug:'egito',                nome:'Egito',                  continente:'África',   coords:{lat:26.8,lng:30.8}, capital:'Cairo'                 },
  { slug:'eritreia',             nome:'Eritreia',               continente:'África',   coords:{lat:15.2,lng:39.8}, capital:'Asmara'                },
  { slug:'eswatini',             nome:'Eswatini',               continente:'África',   coords:{lat:-26.5,lng:31.5},capital:'Mbabane'               },
  { slug:'etiopia',              nome:'Etiópia',                continente:'África',   coords:{lat:9.1,lng:40.5},  capital:'Adis Abeba'            },
  { slug:'gabao',                nome:'Gabão',                  continente:'África',   coords:{lat:-0.8,lng:11.6}, capital:'Libreville'            },
  { slug:'gambia',               nome:'Gâmbia',                 continente:'África',   coords:{lat:13.5,lng:-15.3},capital:'Banjul'                },
  { slug:'gana',                 nome:'Gana',                   continente:'África',   coords:{lat:8.0,lng:-1.0},  capital:'Acra'                  },
  { slug:'guine',                nome:'Guiné',                  continente:'África',   coords:{lat:11.0,lng:-10.9},capital:'Conacri'               },
  { slug:'guine-bissau',         nome:'Guiné-Bissau',           continente:'África',   coords:{lat:12.0,lng:-15.2},capital:'Bissau'                },
  { slug:'guine-equatorial',     nome:'Guiné Equatorial',       continente:'África',   coords:{lat:1.6,lng:10.3},  capital:'Malabo'                },
  { slug:'mauricio',             nome:'Maurício',               continente:'África',   coords:{lat:-20.2,lng:57.5},capital:'Port Louis'            },
  { slug:'quenia',               nome:'Quênia',                 continente:'África',   coords:{lat:0.0,lng:37.9},  capital:'Nairóbi'               },
  { slug:'lesoto',               nome:'Lesoto',                 continente:'África',   coords:{lat:-29.6,lng:28.2},capital:'Maseru'                },
  { slug:'liberia',              nome:'Libéria',                continente:'África',   coords:{lat:6.4,lng:-9.4},  capital:'Monróvia'              },
  { slug:'libia',                nome:'Líbia',                  continente:'África',   coords:{lat:27.0,lng:18.0}, capital:'Trípoli'               },
  { slug:'madagascar',           nome:'Madagascar',             continente:'África',   coords:{lat:-18.8,lng:46.9},capital:'Antananarivo'          },
  { slug:'malawi',               nome:'Malawi',                 continente:'África',   coords:{lat:-13.3,lng:34.3},capital:'Lilongue'              },
  { slug:'mali',                 nome:'Mali',                   continente:'África',   coords:{lat:17.6,lng:-3.9}, capital:'Bamako'                },
  { slug:'marrocos',             nome:'Marrocos',               continente:'África',   coords:{lat:31.8,lng:-7.1}, capital:'Rabat',                paginaEstatica:'marrocos.html'  },
  { slug:'mauritania',           nome:'Mauritânia',             continente:'África',   coords:{lat:20.3,lng:-10.9},capital:'Nuakchote'             },
  { slug:'mocambique',           nome:'Moçambique',             continente:'África',   coords:{lat:-18.7,lng:35.5},capital:'Maputo'                },
  { slug:'namibia',              nome:'Namíbia',                continente:'África',   coords:{lat:-22.0,lng:17.1},capital:'Windhoek'              },
  { slug:'niger',                nome:'Níger',                  continente:'África',   coords:{lat:17.6,lng:8.1},  capital:'Niamey'                },
  { slug:'nigeria',              nome:'Nigéria',                continente:'África',   coords:{lat:9.1,lng:8.7},   capital:'Abuja'                 },
  { slug:'ruanda',               nome:'Ruanda',                 continente:'África',   coords:{lat:-1.9,lng:29.9}, capital:'Kigali'                },
  { slug:'sao-tome',             nome:'São Tomé e Príncipe',    continente:'África',   coords:{lat:0.2,lng:6.6},   capital:'São Tomé'              },
  { slug:'senegal',              nome:'Senegal',                continente:'África',   coords:{lat:14.5,lng:-14.5},capital:'Dacar'                 },
  { slug:'serra-leoa',           nome:'Serra Leoa',             continente:'África',   coords:{lat:8.5,lng:-11.8}, capital:'Freetown'              },
  { slug:'seychelles',           nome:'Seychelles',             continente:'África',   coords:{lat:-4.7,lng:55.5}, capital:'Vitória'               },
  { slug:'somalia',              nome:'Somália',                continente:'África',   coords:{lat:5.2,lng:46.2},  capital:'Mogadíscio'            },
  { slug:'sudao',                nome:'Sudão',                  continente:'África',   coords:{lat:15.6,lng:32.5}, capital:'Cartum'                },
  { slug:'sudao-do-sul',         nome:'Sudão do Sul',           continente:'África',   coords:{lat:6.9,lng:31.3},  capital:'Juba'                  },
  { slug:'tanzania',             nome:'Tanzânia',               continente:'África',   coords:{lat:-6.4,lng:34.9}, capital:'Dodoma'                },
  { slug:'togo',                 nome:'Togo',                   continente:'África',   coords:{lat:8.6,lng:0.8},   capital:'Lomé'                  },
  { slug:'tunisia',              nome:'Tunísia',                continente:'África',   coords:{lat:33.9,lng:9.5},  capital:'Túnis'                 },
  { slug:'uganda',               nome:'Uganda',                 continente:'África',   coords:{lat:1.4,lng:32.3},  capital:'Campala'               },
  { slug:'zambia',               nome:'Zâmbia',                 continente:'África',   coords:{lat:-13.1,lng:27.8},capital:'Lusaka'                },
  { slug:'zimbabue',             nome:'Zimbábue',               continente:'África',   coords:{lat:-19.0,lng:29.2},capital:'Harare'                },

  // ═══════════════════════════════════════════════════ AMÉRICAS
  { slug:'antigua',              nome:'Antígua e Barbuda',      continente:'Américas', coords:{lat:17.1,lng:-61.8},capital:"Saint John's"          },
  { slug:'argentina',            nome:'Argentina',              continente:'Américas', coords:{lat:-38.4,lng:-63.6},capital:'Buenos Aires'         },
  { slug:'bahamas',              nome:'Bahamas',                continente:'Américas', coords:{lat:25.0,lng:-77.4},capital:'Nassau'                },
  { slug:'barbados',             nome:'Barbados',               continente:'Américas', coords:{lat:13.2,lng:-59.6},capital:'Bridgetown'            },
  { slug:'belize',               nome:'Belize',                 continente:'Américas', coords:{lat:17.2,lng:-88.5},capital:'Belmopan'              },
  { slug:'bolivia',              nome:'Bolívia',                continente:'Américas', coords:{lat:-16.3,lng:-63.6},capital:'Sucre'                },
  { slug:'brasil',               nome:'Brasil',                 continente:'Américas', coords:{lat:-14.2,lng:-51.9},capital:'Brasília',            paginaEstatica:'brasil.html'    },
  { slug:'canada',               nome:'Canadá',                 continente:'Américas', coords:{lat:56.1,lng:-106.4},capital:'Ottawa'               },
  { slug:'chile',                nome:'Chile',                  continente:'Américas', coords:{lat:-35.7,lng:-71.5},capital:'Santiago'             },
  { slug:'colombia',             nome:'Colômbia',               continente:'Américas', coords:{lat:4.6,lng:-74.3}, capital:'Bogotá'                },
  { slug:'costa-rica',           nome:'Costa Rica',             continente:'Américas', coords:{lat:9.7,lng:-83.8}, capital:'San José',             paginaEstatica:'costa-rica.html'},
  { slug:'cuba',                 nome:'Cuba',                   continente:'Américas', coords:{lat:21.5,lng:-78.0},capital:'Havana'                },
  { slug:'dominica',             nome:'Dominica',               continente:'Américas', coords:{lat:15.4,lng:-61.4},capital:'Roseau'                },
  { slug:'equador',              nome:'Equador',                continente:'Américas', coords:{lat:-1.8,lng:-78.2},capital:'Quito'                 },
  { slug:'el-salvador',          nome:'El Salvador',            continente:'Américas', coords:{lat:13.8,lng:-88.9},capital:'San Salvador'          },
  { slug:'eua',                  nome:'Estados Unidos',         continente:'Américas', coords:{lat:37.1,lng:-95.7},capital:'Washington D.C.',      paginaEstatica:'eua-parques.html'},
  { slug:'granada',              nome:'Granada',                continente:'Américas', coords:{lat:12.1,lng:-61.7},capital:"Saint George's"        },
  { slug:'guatemala',            nome:'Guatemala',              continente:'Américas', coords:{lat:15.8,lng:-90.2},capital:'Cidade da Guatemala'   },
  { slug:'guiana',               nome:'Guiana',                 continente:'Américas', coords:{lat:4.9,lng:-58.9}, capital:'Georgetown'            },
  { slug:'haiti',                nome:'Haiti',                  continente:'Américas', coords:{lat:18.9,lng:-72.3},capital:'Porto Príncipe'        },
  { slug:'honduras',             nome:'Honduras',               continente:'Américas', coords:{lat:15.2,lng:-86.2},capital:'Tegucigalpa'           },
  { slug:'jamaica',              nome:'Jamaica',                continente:'Américas', coords:{lat:18.1,lng:-77.3},capital:'Kingston'              },
  { slug:'mexico',               nome:'México',                 continente:'Américas', coords:{lat:23.6,lng:-102.6},capital:'Cidade do México'     },
  { slug:'nicaragua',            nome:'Nicarágua',              continente:'Américas', coords:{lat:12.9,lng:-85.2},capital:'Manágua'               },
  { slug:'panama',               nome:'Panamá',                 continente:'Américas', coords:{lat:8.5,lng:-80.8}, capital:'Cidade do Panamá'      },
  { slug:'paraguai',             nome:'Paraguai',               continente:'Américas', coords:{lat:-23.4,lng:-58.4},capital:'Assunção'             },
  { slug:'patagonia',            nome:'Patagônia',              continente:'Américas', coords:{lat:-51.0,lng:-72.5},capital:'—',                   paginaEstatica:'patagonia.html' },
  { slug:'peru',                 nome:'Peru',                   continente:'Américas', coords:{lat:-9.2,lng:-75.0},capital:'Lima'                  },
  { slug:'republica-dominicana', nome:'República Dominicana',   continente:'Américas', coords:{lat:18.7,lng:-70.2},capital:'Santo Domingo'         },
  { slug:'santa-lucia',          nome:'Santa Lúcia',            continente:'Américas', coords:{lat:13.9,lng:-60.9},capital:'Castries'              },
  { slug:'sao-cristovao',        nome:'São Cristóvão e Névis',  continente:'Américas', coords:{lat:17.4,lng:-62.8},capital:'Basseterre'            },
  { slug:'sao-vicente',          nome:'São Vicente e Granadinas',continente:'Américas',coords:{lat:13.3,lng:-61.2},capital:'Kingstown'             },
  { slug:'suriname',             nome:'Suriname',               continente:'Américas', coords:{lat:3.9,lng:-56.0}, capital:'Paramaribo'            },
  { slug:'trinidad',             nome:'Trinidad e Tobago',      continente:'Américas', coords:{lat:10.7,lng:-61.2},capital:'Porto de Espanha'      },
  { slug:'uruguai',              nome:'Uruguai',                continente:'Américas', coords:{lat:-32.5,lng:-55.8},capital:'Montevidéu'           },
  { slug:'venezuela',            nome:'Venezuela',              continente:'Américas', coords:{lat:6.4,lng:-66.6}, capital:'Caracas'               },

  // ═══════════════════════════════════════════════════ OCEANIA
  { slug:'australia',            nome:'Austrália',              continente:'Oceania',  coords:{lat:-25.3,lng:133.8},capital:'Camberra'             },
  { slug:'fiji',                 nome:'Fiji',                   continente:'Oceania',  coords:{lat:-17.7,lng:178.1},capital:'Suva'                 },
  { slug:'ilhas-marshall',       nome:'Ilhas Marshall',         continente:'Oceania',  coords:{lat:7.1,lng:171.2}, capital:'Majuro'                },
  { slug:'ilhas-salomao',        nome:'Ilhas Salomão',          continente:'Oceania',  coords:{lat:-9.6,lng:160.2},capital:'Honiara'               },
  { slug:'kiribati',             nome:'Kiribati',               continente:'Oceania',  coords:{lat:1.9,lng:157.4}, capital:'Tarawa'                },
  { slug:'micronesia',           nome:'Micronésia',             continente:'Oceania',  coords:{lat:7.4,lng:150.6}, capital:'Palikir'               },
  { slug:'nauru',                nome:'Nauru',                  continente:'Oceania',  coords:{lat:-0.5,lng:166.9},capital:'Yaren'                 },
  { slug:'nova-zelandia',        nome:'Nova Zelândia',          continente:'Oceania',  coords:{lat:-40.9,lng:174.9},capital:'Wellington'           },
  { slug:'palau',                nome:'Palau',                  continente:'Oceania',  coords:{lat:7.5,lng:134.6}, capital:'Ngerulmud'             },
  { slug:'papua',                nome:'Papua Nova Guiné',       continente:'Oceania',  coords:{lat:-6.3,lng:143.9},capital:'Port Moresby'          },
  { slug:'samoa',                nome:'Samoa',                  continente:'Oceania',  coords:{lat:-13.8,lng:-172.1},capital:'Apia'                },
  { slug:'tonga',                nome:'Tonga',                  continente:'Oceania',  coords:{lat:-21.2,lng:-175.2},capital:'Nukualofa'           },
  { slug:'tuvalu',               nome:'Tuvalu',                 continente:'Oceania',  coords:{lat:-7.1,lng:179.2},capital:'Funafuti'              },
  { slug:'vanuatu',              nome:'Vanuatu',                continente:'Oceania',  coords:{lat:-15.4,lng:166.9},capital:'Port Vila'            },

].map(p => ({ ...p, status: p.paginaEstatica ? 'publicado' : 'em-breve' }));
